project:
  type: website

website:
  title: "Pouet"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      

format:
  html:
    # theme: sandstone
    theme: simplex
    css: styles.css
    toc: true



